Super+W: Ctrl+W
Super+Q: Ctrl+Q
Super+C: Ctrl+C
Super+V: Ctrl+V
Super+X: Ctrl+X
Super+Z: Ctrl+Z
Super+Left: Home
Super+Right: End
Super+Shift+Left: Shift+Home
Super+Shift+Right: Shift+End
Meta+Left: Ctrl+Left
Meta+Right: Ctrl+Right
Meta+Shift+Left: Ctrl+Shift+Left
Meta+Shift+Right: Ctrl+Shift+Right
